kind: Pod
apiVersion: v1

metadata:
  name: user05-nvhpc-gpu_cluster

spec:
  # Add the server as an NFS volume for the pod
  volumes:
    - name: nfs-volume
      nfs:
        # URL for the NFS server
        server: 152.118.31.24 # Change this!
        path: /mnt/sharedfolder/user05

  # In this container, we'll mount the NFS volume
  # and write the date to a file inside it.
  containers:
    - name: app
      image: nvcr.io/nvidia/nvhpc:22.9-devel-cuda11.7-ubuntu22.04

      # Mount the NFS volume in the container
      volumeMounts:
        - name: nfs-volume
          mountPath: /workspace

      # Write to a file inside our NFS
      command: ["/bin/sh"]
      args: ["-c", "while true; do date >> /workspace/date.txt; sleep 5; done"]

  nodeSelector:
    gputype: gpu-02

  imagePullSecrets:
    - name: nvcr.dgxkey
